training:
  model: "FashionMNISTModelV2"
  criterion: "CrossEntropyLoss"
  optimizer: "SGD"
  epochs: 2
  learning_rate: 0.1
  batch_size: 32

model:
  FashionMNISTModelV2:
    hidden_neurons: 30 

meta:
  data_save_path: "data/"
